### DISCUSSION TITLE
Expose this role in a galaxy collection

### DISCUSSION THREAD

**Discussion by evrardjp** [evrardjp/ansible-keepalived#219] [Ideas]
Without a galaxy collection, this role will always be considered as a second citizen.

Currently, the galaxy content searches inside collections first. Tthe standalone roles are relegated to page 2 (minimum), after the collections. That always apply, even if you sort by the amount of downloads (in which this role should be first).

Quote from the ansible website:
"You must migrate roles to collections if you want to distribute them as certified Ansible content." 

I think it might make sense to expose this role inside a galaxy collection, but I feel it will be a pain to manage... Any idea?

**Comment by Kariton** [comment]
What is the goal of "this" collection?
and what do you want do include beside keepalived?

I know that LVS / IPVS is a nice addition.
- ``evrardjp.SOMETHING.keeplaived``
- ``evrardjp.SOMETHING.lvs``
- ``evrardjp.SOMETHING.lvs_realserver_maintenance``
(to reference my usecase with this role)

so someone could do stuff like this:
```yaml
---

- hosts: loadbalancers, host.example.tld
  tasks:
#    - name: "configure keepalived"
#      ansible.builtin.import_role:
#       name: evrardjp.SOMETHING.keeplaived
#      when: "'loadbalancers' in group_names"

#    - name: "configure lvs"
#      ansible.builtin.import_role:
#       name: evrardjp.SOMETHING.lvs
#      when: "'loadbalancers' in group_names"

    - name: "set lvs RS maintenance"
      ansible.builtin.import_role:
        name: evrardjp.SOMETHING.lvs_realserver_maintenance
        vars:
          state: true # lvsadm cli command - not persistent
          # state: persistent # keepalived (re)configuration through 'evrardjp.SOMETHING.keeplaived' - is persistent (im aware that ipvsadm can also be used in a persistent way without keepalived.
          realserver: 'host.example.tld'
      when: "'loadbalancers' in group_names"

    - name: "do stuff on RS"
      ansible.builtin.import_role:
        name: some_role
      when: "'loadbalancers' not in group_names"

    - name: "unset lvs RS maintenance"
      ansible.builtin.import_role:
        name: evrardjp.SOMETHING.lvs_realserver_maintenance
        vars:
          state: false
          realserver: 'host.example.tld'
      when: "'loadbalancers' in group_names"

```
which would be the equivalent of my use case (provided example in this discussion: https://github.com/evrardjp/ansible-keepalived/discussions/222)

this would only save the "include sub playbook" for the user.
the workflow will be the same.

I thing a quiet easy step would be to create a "single role collection"
``evrardjp.SOMETHING.keeplaived``


_justmy2cents_
