### ISSUE TITLE
Role does not find variables when executing unrelated tasks

### ISSUE THREAD

**Issue by in0rdr** [evrardjp/ansible-keepalived#153]
This is a follow-up issue for https://github.com/evrardjp/ansible-keepalived/pull/152.

When the role is included in a playbook with various tasks (used as tagged "snippets"), the role breaks the execution of the snippets, tagged "some-other-tasks" in the example below, because the [`with_first_found` in combination with `include_vars`](https://github.com/evrardjp/ansible-keepalived/blob/master/tasks/main.yml) is unable to find the "var files".

Example playbook:
```yaml
# these tasks existed before the playbook was amended by the keepalived role below
- hosts: all
  tags: some-other-tasks
  become: yes
  tasks:
    - debug: msg=test

# the keepalived role was added in hindsight with the expectation,
# that the tasks above should continue running as before the placement of the role here
- hosts: haproxy
  tags: keepalived
  become: yes
  roles:
    - { role: keepalived }
```

The behavior of task snippets unrelated to the keepalived role should be unaffected by the role:
```bash
ansible-playbook -i dev/inventory playbook.yml -t some-other-tasks
```

Expected output: The task snippets should run as before the placement of the keepalived role in the playbook

Actual output: The task snippets cannot be executed anymore after the placement of the keepalived role in the playbook together with the snippets. The followin error msg occurs:
```
No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found
```

Workaround 1, skip `always` tag, because the variables are not needed anyways to execute `some-other-tasks` only:
```
ansible-playbook -i dev/inventory playbook.yml -t some-other-tasks --skip-tags=always
```

Workaround 2, create different playbook files for the snippets and the keepalived role.
