### ISSUE TITLE
service control enhancement

### ISSUE THREAD

**Issue by jardleex** [evrardjp/ansible-keepalived#20]
Hello @evrardjp,

I've noticed that the role does not take care of the actual service status and its start behavior on reboot
May you add enhance the role with something like:

````
- name: Make sure keepalived is running and enabled if set
  service:
    name: keepalived
    state: started
    enabled: "{{ keepalived_service_enabled | default(omit) }}"
  when: keepalived_service_control
````

Improvement ideas on this snippet are welcome. I did not test this snippet yet.

Best regards

Jard
