### ISSUE TITLE
Change keepalived_service_name for Ubuntu 16

### ISSUE THREAD

**Issue by jardleex** [evrardjp/ansible-keepalived#33]
Hello,

I just noticed that the roles does not enable the autostart of the keeplaived service on Ubuntu 16.

When:
````
keepalived_service_name: "keepalived.service"
# instead of
keepalived_service_name: "keepalived"
````

is set then it works. Can you verify this and maybe change `keepalived_service_name` in `vars/ubuntu-16.04.yml`?

Thank you in advance

Best regards
Jard

**Comment by evrardjp** [comment]
I'll verify this today.

**Comment by evrardjp** [comment]
I didn't change anything on my system, and the service auto starts on boot.

**Comment by evrardjp** [comment]
Could it be possible that something happened during your first run, and the override to prevent restart was still there?

https://github.com/evrardjp/ansible-keepalived/blob/master/tasks/keepalived_install_apt.yml#L67-L83

**Comment by jardleex** [comment]
I think I know what happened here.

I deploy the systemd unit file from keepalived version 1.2.24 in a dedicated task as the current version 1.2.23 does not provide one and I had issues on that in the beginning.

When I use the role naked I get:
````
root@dnsmasq03:~# systemctl status keepalived
● keepalived.service - LSB: Starts keepalived
● keepalived.service - LSB: Starts keepalived
● keepalived.service - LSB: Starts keepalived
   Loaded: loaded (/etc/init.d/keepalived; bad; vendor preset: enabled)
   Active: active (running) since Di 2017-01-31 14:25:51 UTC; 9s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1037 ExecStart=/etc/init.d/keepalived start (code=exited, status=0/SUCCESS)
    Tasks: 18
   Memory: 10.7M
      CPU: 189ms
   CGroup: /system.slice/keepalived.service
           ├─1072 /usr/sbin/keepalived
           ├─1073 /usr/sbin/keepalived
           ├─1074 /usr/sbin/keepalived
....
````

With this the autostart works indeed. 

I do in addition:
````
    - name: GET_URL | fetch systemd unit file not included in 1.2.23 yet
      get_url:
        url: 'https://raw.githubusercontent.com/acassen/keepalived/v1.2.24/keepalived/keepalived.service'
        dest: '/etc/systemd/system/keepalived.service'
        checksum: 'md5:da851c03bcedafc35129078ba5046e06'
        mode: 0644
      notify:
        - reload systemd
        - restart keepalived
````

Which leads to:
````
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/etc/systemd/system/keepalived.service; disabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-01-31 13:05:52 UTC; 1h 23min ago
  Process: 24278 ExecStart=/usr/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 24279 (keepalived)
    Tasks: 3
   Memory: 4.1M
      CPU: 3min 21.136s
   CGroup: /system.slice/keepalived.service
           ├─24279 /usr/sbin/keepalived -D
           ├─24281 /usr/sbin/keepalived -D
           └─24282 /usr/sbin/keepalived -D

````
Here it helped me to set ``keepalived_service_name: "keepalived.service"`` in ``vars/ubuntu-16.04.yml``. But as it is define in vars, I can't override it my group or host_vars [Variable precedence](https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

So the issue is related to the fact that I use a dedicated systemd unit file instead of the default init script.
I assume when keepalived version 1.2.24 is in the PPA more people may face the issue.
