### ISSUE TITLE
Do not start keepalived after installation

### ISSUE THREAD

**Issue by berendt** [evrardjp/ansible-keepalived#5]
I want to propose to not start the ``keepavlied`` service after the installation.

When using this role at the moment I have 3 additional addresses assigned to eth0 after the installation. Those 3 addresses are used in the default ``keepalived.conf`` configuration file of Ubuntu.

```
    inet 192.168.200.16/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.17/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.18/32 scope global eth0
       valid_lft forever preferred_lft forever
```

For Ubuntu 14.04 you can use the following command to disable the start of the service after the installlation.

```
- name: do not start keepalived after installation
  copy:
    dest: /etc/init/keepalived.override
    content: manual
```
